name: A workflow for Group Project
on: push

jobs:
  build:
    name: Group Project
    runs-on: ubuntu-22.04

    services:
      mysql:
        image: mysql:8.0
        ports: ['3306:3306']
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: world
          MYSQL_USER: user
          MYSQL_PASSWORD: pass
        options: >-
          --health-cmd="mysqladmin ping -proot || exit 1"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install MySQL client
        run: sudo apt-get update && sudo apt-get install -y mysql-client

      - name: Wait for MySql and import data
        run: |
          for i in {1..60}; do
            if mysql -h 127.0.0.1 -u root -proot -e "SELECT 1" &>/dev/null; then
              echo "MySQL is ready"; break
            fi
            sleep 2
          done

          mysql -h 127.0.0.1 -u root -proot world < data/world.sql

      - name: Package with Maven
        run: mvn -B -DskipTests package

      - name: Build Docker Image
        run: docker build -t devopsimage .

      - name: Run application (generate markdown)
        run: |
          docker run --name reportsapp \
            --network host \
            -e DB_HOST=127.0.0.1 \
            -e DB_PORT=3306 \
            -e DB_NAME=world \
            -e DB_USER=user \
            -e DB_PASS=pass \
            devopsimage

      - name: Unit Tests
        run: mvn -Dtest="com.napier.sem.DatabaseManagerTest,com.napier.sem.ReportServiceTest" test

      - name: Integration Tests
        run: mvn -Dtest=com.napier.sem.IntegrationTests test

      ############################################################
      # LAB 08 DEPLOYMENT STEPS
      ############################################################

      - name: Copy Markdown Reports From Container
        run: |
          mkdir -p reports
          docker container cp reportsapp:/tmp/reports ./reports || echo "No markdown reports generated"

      - name: Deploy Release JAR
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "latest"
          files: ./target/app.jar

      - name: Deploy Markdown Reports to Branch
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: reports
          folder: reports
